language: cpp

branches:
  except:
  - travis/*

before_install:
- eval "${MATRIX_EVAL}"

script:
- mkdir build-travis
- cd build-travis
- cmake .. -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DUSE_LIBCXX=ON -DSIMPLE_SOCKET_TEST=ON
- make -j3
- "./tests/Simple-Socket-Tester.run"

jobs:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-8
        packages:
        - clang-8
        - libc++-8-dev
        - libc++abi-8-dev
    env:
    - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"
    
  - os: linux
    dist: xenial
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty-7
        packages:
        - libc++-7-dev
        - libc++abi-7-dev
    env:
    - MATRIX_EVAL="CC=clang && CXX=clang++"
    
  - os: linux
    dist: trusty
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    
  - os: linux
    dist: xenial
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-8
    env:
    - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-9
    env:
    - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
    
  - os: osx
    osx_image: xcode10.2
    env:
    - MATRIX_EVAL=""

  - os: osx
    osx_image: xcode10
    env:
    - MATRIX_EVAL=""
    
  - os: osx
    osx_image: xcode9.4
    env:
    - MATRIX_EVAL=""
    
  - stage: Coverage
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
        - lcov
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    script:
    - mkdir build-travis
    - cd build-travis
    - cmake .. -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=Debug
      -DSIMPLE_SOCKET_EXAMPLES=OFF -DSIMPLE_SOCKET_COVERAGE=ON
    - make coverage
    after_success:
    - gem install coveralls-lcov
    - coveralls-lcov coverage.info.cleaned
    - curl -X PURGE https://camo.githubusercontent.com/17f413e2bbe682cd351ce70ca2f36765393e99f5/68747470733a2f2f636f766572616c6c732e696f2f7265706f732f6769746875622f7072696e63652d63687269736d632f53696d706c652d536f636b65742f62616467652e7376673f6272616e63683d6d6173746572

  - stage: Lint
    dist: xenial
    language: python
    python:
    - "3.7"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-8
        packages:
        - cppcheck
        - clang-8
        - clang-tidy-8
        - libc++-8-dev
        - libc++abi-8-dev
    env:
    - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"
    script:
    - git config --global user.email "travis@travis-ci.org" && git config --global user.name "Travis CI"
    - git checkout -b travis/${TRAVIS_BRANCH}_${TRAVIS_BUILD_NUMBER}
    - sudo -H pip install cmake-format
    - ./ci/format-cmake.sh
    - git add -u
    - git diff-index --quiet HEAD || ( git commit -m "cmake-formatted by ci"
      && git remote add origin-ci https://${GH_TOKEN}@github.com/prince-chrismc/Simple-Socket.git
      && git push --set-upstream origin-ci )
    - mkdir build-travis && cd build-travis
    - cmake .. -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DSIMPLE_SOCKET_EXAMPLES=OFF -DSIMPLE_SOCKET_LINT=ON
    - make
    #- make cppcheck # incorrect version gets installed

  - stage: Legacy
    dist: trusty
    script:
    - mkdir build-travis
    - cd build-travis
    - cmake .. -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DSIMPLE_SOCKET_EXAMPLES=OFF -DSIMPLE_SOCKET_STRING_VIEW=OFF

  - stage: Legacy
    dist: xenial
    script:
    - mkdir build-travis
    - cd build-travis
    - cmake .. -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DSIMPLE_SOCKET_EXAMPLES=OFF -DSIMPLE_SOCKET_STRING_VIEW=OFF
      
  - stage: Legacy
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-4.0
        packages:
        - clang-4.0
        - lldb-4.0
        - lld-4.0
        - libc++1
    env:
    - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
    script:
    - mkdir build-travis
    - cd build-travis
    - cmake .. -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DUSE_LIBCXX=ON -DSIMPLE_SOCKET_EXAMPLES=OFF
      -DSIMPLE_SOCKET_STRING_VIEW=OFF

  - stage: Legacy
    os: osx
    osx_image: xcode8.3
    env:
      - MATRIX_EVAL=""
    script:
    - mkdir build-travis
    - cd build-travis
    - cmake .. -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DUSE_LIBCXX=ON -DSIMPLE_SOCKET_EXAMPLES=OFF
      -DSIMPLE_SOCKET_STRING_VIEW=OFF

notifications:
  slack:
    secure: MSZB2wEMSbXrFUu6OmlD38MZmHDO5eW33SLBGU45QL123wfy2jEA5ZbGNoTyv8u+nBmP/dSjlEjXQ6QrCsBlSFpsdwzSwuEVn5Naq3f4uNmD1N0cZu8MDaU0UIuRz58ODJfUcMG/422QbjUEhRjCBlX7XMNGgb89y+XQfvcxqi/vwu3NSWz7hZFTswR70453S38HvznoCQiZfZm1s4OJ7zpsBzhLqI8Qe7MjvSAOlQ9e3Td6G69qSMby0NoQlFJzW3J7OAiIU0+HJ7CQdZg7Qczcj5L/NqQ6lXsgXXt8OB+A8yUa4UuBOgg5X7/ILVUhBgEVlavvG8NW8IocHWZ2+Dg6taC2LYHI70KQybRWB2X10VJ/d5n0svLWfcCTllQ9irrVnE+i49xzooarajsO3MPXuE0nGXsfgTsPwtT6OxYd68jLPIlsBM0SDQQPZa6H8LBIOKHZMNPwjDIE3jJ/40e4j/pU13juH267O2tgGAyRQFAeq54INUKUvlJUNxzRRt8KLMcnm2ctUlrNvBkkzgX86TlVU7W+EttRKEnbA2OgUCzvIaIe1hEIFzNjged5Gxi6zgivSIAz2QwEP9n0jswMokaI5DAX+Doe6JZPSXQ/CnAzu+LkdS6NYq8PUA+QgBKG87W1XILvy5EqhZtvbMahBhvchYpXCPf7FZtAFCE=
  email: false
